services:

  application:
    container_name: payroll-app
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    image: untilov/payroll
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./db.sqlite:./db.sqlite

  reverse-proxy:
    container_name: payroll-nginx
    build:
      context: .
      dockerfile: ./packages/nginx/Dockerfile
    image: untilov/nginx
    restart: always
    ports:
      - 80:80

